config/routes.rb
Rails.application.routes.draw do
  root 'blog_posts#index'

  devise_for :users, path: '', path_names: { sign_in: 'login' }
  get 'logout', to: 'pages#logout', as: 'logout'

  resources :subscribe, only: [:index]
  resources :dashboard, only: [:index]
  resources :account, only: [:index, :update]
  #resources :billing_portal, only: [:new, :create]
  resources :blog_posts, controller: :blog_posts, path: "blog", param: :slug
  resources :blog_posts, only: [:show, :index]


  # static pages
  pages = %w[
    privacy terms
  ]

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: page.gsub('-', '_').to_s
  end

  # admin panels
  authenticated :user, ->(user) { user.admin? } do
    namespace :admin do
      resources :dashboard, only: [:index]
      resources :impersonations, only: [:new]
      resources :users, only: [:edit, :update, :destroy]
    end

    # convenience helper
    get 'admin', to: 'admin/dashboard#index'

    # about page
    get 'about', to: 'pages#about'
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all.order(created_at: :desc)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/views/admin/dashboard/index.html.erb
<%= render partial: "shared/heading", locals: { title: 'Admin Dashboard', description: '' } %>

<div class="max-w-3xl mx-auto px-4">
  <div class="mb-4">
    <h3 class="font-semibold">Signups</h3>
    <%= line_chart User.where(created_at: 3.months.ago..Time.now).group_by_week(:created_at).count %>
  </div>

  <div class="overflow-x-auto">
    <div class="py-2 align-middle inline-block sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="divide-y divide-gray-200 border">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                signed up (ET)
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                email
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                paying customer?
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                actions
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                impersonate
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @users.each do |user| %>
              <tr>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  <%= user.created_at.in_time_zone('Eastern Time (US & Canada)').strftime('%F %H:%M') %>
                </td>
                <td class="px-6 py-4 whitespace-wrap text-sm text-gray-500">
                  <%= user.email %>
                </td>
                <td class="px-6 py-4 whitespace-wrap text-sm text-gray-500">
                  <%= user.paying_customer? %>
                </td>
                <td class="px-6 py-4 whitespace-wrap text-sm text-gray-500">
                  <%= link_to 'edit', edit_admin_user_path(id: user.id), class: 'text-primary-500' %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  <%= link_to new_admin_impersonation_path(user_id: user.id) do %>
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                  </svg>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>