config/routes.rb
Rails.application.routes.draw do
  root 'blog_posts#index'

  devise_for :users, path: '', path_names: { sign_in: 'login' }
  get 'logout', to: 'pages#logout', as: 'logout'

  resources :subscribe, only: [:index]
  resources :dashboard, only: [:index]
  resources :account, only: [:index, :update]
  #resources :billing_portal, only: [:new, :create]
  resources :blog_posts, controller: :blog_posts, path: "blog", param: :slug
  resources :blog_posts, only: [:show, :index]


  # static pages
  pages = %w[
    privacy terms
  ]

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: page.gsub('-', '_').to_s
  end

  # admin panels
  authenticated :user, ->(user) { user.admin? } do
    namespace :admin do
      resources :dashboard, only: [:index]
      resources :impersonations, only: [:new]
      resources :users, only: [:edit, :update, :destroy]
    end

    # convenience helper
    get 'admin', to: 'admin/dashboard#index'

    # about page
    get 'about', to: 'pages#about'
  end
end

app/views/shared/_flash.html.erb
<% if notice || alert %>
  <div class="md:grid md:grid-cols-3 md:gap-6 mt-12">
    <div class="md:col-span-1"></div>
    <div class="flex justify-center">

      <div id="flash-toast" class="fixed z-20 flex mx-auto top-5 items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow-md border border-gray-100 animate-[flashfade_4s_both]" data-controller="removals" data-action="animationend->removals#remove" role="alert">
        <div class="<%= flash_classes %> inline-flex items-center justify-center flex-shrink-0 w-8 h-8 rounded-lg">
          <%== flash_icon %>
        </div>
        <div class="ml-3 text-sm font-normal"><%= notice || alert %></div>
        <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8" data-dismiss-target="#flash-toast" aria-label="Close" onclick="this.parentElement.remove()">
          <span class="sr-only">Close</span>
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    // Remove flash messages after the animation ends
    document.addEventListener('animationend', function(event) {
      if (event.animationName === 'flashfade') {
        event.target.remove();
      }
    });
  </script>
<% end %>

app/views/shared/_header.html.erb
<header class="py-4 px-2" data-controller="header">
  <nav class="flex items-center justify-between flex-wrap">
    <div class="flex items-center flex-no-shrink text-white mr-6">
      <% logo_path = current_user ? dashboard_index_path : root_path %>
      <%= link_to logo_path, class:"flex items-center hover:opacity-80" do %>
        <span class="font-semibold text-xl tracking-tight text-primary-600"><%= ENV['COMPANY_NAME'] %></span>
      <% end %>
    </div>
    <div class="block sm:hidden">
      <button class="navbar-burger flex items-center px-3 py-2 border rounded text-white border-white hover:text-white hover:border-white" data-action="click->header#toggleMobileNav">
        <svg class="text-black fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
        </svg>
      </button>
    </div>

    <div id="main-nav" class="w-full flex-grow sm:flex text-right sm:w-auto hidden" data-header-target="mainNav">
      <div class="text-sm sm:flex-grow">
        <%= link_to 'Blog', blog_posts_path, class: nav_link_classes('blog') %>
        <% if current_user %>
          <%= link_to 'Admin', admin_dashboard_index_path, class: nav_link_classes('admin/dashboard') if current_user.admin? %>
          <%= link_to 'Dashboard', dashboard_index_path, class: nav_link_classes('dashboard') %>
          <%= link_to 'Account', account_index_path, class: nav_link_classes('account') %>
          <%= link_to 'Logout', logout_path, class: nav_link_classes %>
          <%= link_to 'About', about_path, class: nav_link_classes('about') %>    
        <% end %>
      </div>
    </div>
  </nav>
</header>


<!-- smooth scroll nav links -->
<script type="text/javascript">
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
          e.preventDefault();

          document.querySelector(this.getAttribute('href')).scrollIntoView({
              behavior: 'smooth'
          });
      });
  });
</script>

app/views/shared/_heading.html.erb
<% description ||= '' %>
<div class="text-center mb-4">
  <h1 class="mt-1 font-extrabold text-gray-900 text-4xl sm:text-4xl sm:tracking-tight lg:text-5xl"><%= title %></h1>
  <p class="max-w-xl mt-5 mx-auto text-xl text-gray-500"><%= description.html_safe %></p>
</div>

app/views/shared/_script_tags.html.erb
<script type="text/javascript">
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
          e.preventDefault();

          document.querySelector(this.getAttribute('href')).scrollIntoView({
              behavior: 'smooth'
          });
      });
  });
</script>