config/routes.rb
Rails.application.routes.draw do
  root 'blog_posts#index'

  devise_for :users, path: '', path_names: { sign_in: 'login' }
  get 'logout', to: 'pages#logout', as: 'logout'

  resources :subscribe, only: [:index]
  resources :dashboard, only: [:index]
  resources :account, only: [:index, :update]
  #resources :billing_portal, only: [:new, :create]
  resources :blog_posts, controller: :blog_posts, path: "blog", param: :slug
  resources :blog_posts, only: [:show, :index]


  # static pages
  pages = %w[
    privacy terms
  ]

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: page.gsub('-', '_').to_s
  end

  # admin panels
  authenticated :user, ->(user) { user.admin? } do
    namespace :admin do
      resources :dashboard, only: [:index]
      resources :impersonations, only: [:new]
      resources :users, only: [:edit, :update, :destroy]
    end

    # convenience helper
    get 'admin', to: 'admin/dashboard#index'

    # about page
    get 'about', to: 'pages#about'
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Signupable
  include Onboardable
  include Billable

  scope :subscribed, -> { where.not(stripe_subscription_id: [nil, '']) }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def edit; end

  def update
    @user.update(user_params)
    redirect_to edit_admin_user_path(id: @user.id), notice: 'User updated successfully.'
  end

  def destroy
    email = @user.email
    DestroyUser.new(@user).call
    redirect_to admin_dashboard_index_path, notice: "User '#{email}' was destroyed."
  end

  private

  def set_user
    @user = User.find_by_id(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :admin)
  end
end

app/views/admin/users/_profile.html.erb
<%= form_for(@user, url: admin_user_path(id: @user.id)) do |f| %>
  <div class="mb-2">
    <label for="company_name">Email Address</label>
    <%= f.text_field :email, required: true, class: "appearance-none rounded-b-md rounded-t-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:border-primary-300 focus:z-10 sm:text-sm sm:leading-5", placeholder: "Acme Co" %>
  </div>

  <div class="form-check">
    <%= f.check_box :admin, class: 'form-check-input appearance-none h-4 w-4 border border-gray-300 rounded-sm bg-white checked:bg-primary-600 checked:border-primary-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer' %>
    <label class="cursor-pointer form-check-label inline-block text-gray-800" for="user_admin">
      Admin?
    </label>
  </div>

  <div class="mt-6">
    <button type="submit" data-turbo="false" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:border-primary-700 transition duration-150 ease-in-out">
      Update
    </button>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="flex">
  <div class="mx-auto">
    <div class="text-center">
      <h3 class="text-xl mb-4">Editing user "<%= @user.email %>"</h3>
      <%= button_to "Delete", admin_user_path(id: @user.id), form: { data: { turbo_confirm: "Are you sure? This will delete the user forever." } }, method: :delete, class: 'text-xs text-white bg-red-500 p-2 rounded-md' %>
    </div>

    <%= render 'profile', user: @user %>
  </div>
</div>